name: okhttp_scrape
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  html: ^0.15.4
  okhttp:
    git:
      url: https://github.com/Noobware1/okhttp.git
      ref: master
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
